export const METADATA_KEYS = {
  CONTROLLER: 'decorator:meta:controller',
  COMMAND: 'decorator:meta:command',
  NET_EVENT: 'decorator:meta:net_event',
  NET_RPC: 'decorator:meta:net_rpc',
  TICK: 'decorator:meta:tick',
  INTERNAL_EVENT: 'decorator:meta:internal_event',
  RUNTIME_EVENT: 'decorator:meta:runtime_event',
  EXPORT: 'decorator:meta:export',
  PUBLIC: 'decorator:meta:public',
  THROTTLE: 'decorator:throttle',
  REQUIRES_STATE: 'decorator:requires_state',
  BINARY_SERVICE: 'decorator:meta:binary_service',
  BINARY_SERVICE_NAME: 'decorator:meta:binary_service_name',
  BINARY_CALL: 'decorator:meta:binary_call',
}
